services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '${EXPOSE_APP_PORT:-15100}:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    command: ["sh", "-c", "npm run db:migrate:run default && npm run start:prod"]

  postgres:
    image: postgres:13
    ports:
      - '${EXPOSE_POSTGRES_PORT:-15432}:5432'
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT:-8080}:8080

volumes:
  postgres-volume:
